AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL/PostgreSQL??Secrets Manager?????

Parameters:

  DBInstanceName:
    Type: String
    Default: rds

  DatabaseEngine:
    Type: String
    Default: MySQL
    AllowedValues:
      - MySQL
      - postgres
    Description: '????????????????????'

  DBInstanceClass:
    Type: String
    Default: db.t3.micro

  DBInstanceStorageSize:
    Type: String
    Default: '30'

  DBInstanceStorageType:
    Type: String
    Default: gp2

  DBName:
    Type: String
    Default: db

  DBMasterUserName:
    Type: String
    Default: dbuser
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    Default: dbpassword
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  # Multi-AZ
  MultiAZ:
    Default: 'true'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  IsMySQL: !Equals
    - !Ref DatabaseEngine
    - MySQL
  IsPostgreSQL: !Equals
    - !Ref DatabaseEngine
    - PostgreSQL

Resources:
  # ------------------------------------------------------------#
  #  Security Group???
  # ------------------------------------------------------------#
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-${DBInstanceName}-sg
      GroupDescription: RDS SG
      VpcId: !ImportValue VpcId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${DBInstanceName}-sg

  # Security Group Ingress???
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt RDSSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: !If
        - IsMySQL
        - 3306
        - 5432
      ToPort: !If
        - IsMySQL
        - 3306
        - 5432
      SourceSecurityGroupId: !GetAtt RDSSecurityGroup.GroupId

  # ------------------------------------------------------------#
  #  RDS
  # ------------------------------------------------------------#
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-${DBInstanceName}
      Engine: !Ref DatabaseEngine
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBInstanceStorageSize
      StorageType: !Ref DBInstanceStorageType
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: !Ref MultiAZ
      PreferredBackupWindow: 18:00-18:30
      PreferredMaintenanceWindow: sat:19:00-sat:19:30
      AutoMinorVersionUpgrade: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 7
      KmsKeyId: !ImportValue KMSKeyId
      StorageEncrypted: true
      DeletionProtection: true
      Tags:
        - Key: !ImportValue TagKey
          Value: !ImportValue TagValue
    DeletionPolicy: Delete

  # ------------------------------------------------------------#
  #  DBSubnetGroup
  # ------------------------------------------------------------#
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${AWS::StackName}-${DBInstanceName}-subnet
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !ImportValue PrivateSubnet3Id
        - !ImportValue PrivateSubnet4Id

  # ------------------------------------------------------------#
  #  Secrets Manager
  # ------------------------------------------------------------#
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: DBInstance
    Properties:
      Name: !Sub ${AWS::StackName}-${DBInstanceName}-secret
      Description: RDS???????????
      SecretString: !Sub |
        {
          "username": "${DBMasterUserName}",
          "password": "${DBPassword}",
          "dbname": "${DBName}",
          "host":  "${DBInstance.Endpoint.Address}"
        }
      KmsKeyId: !ImportValue KMSKeyId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${DBInstanceName}-secret
