apiVersion: v1
kind: Secret
metadata:
  name: cluster-oyaizu-eks-spoke-prod
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: oyaizu-eks-spoke-prod
  server: arn:aws:eks:us-east-1:140083316867:cluster/oyaizu-eks-spoke-prod
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
