apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spoke-registration-oyaizu-eks-spoke-prod
  namespace: fleet-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: spoke-registration-oyaizu-eks-spoke-prod
    creationPolicy: Owner
  data:
    - secretKey: clusterName
      remoteRef:
        key: /fleet/members/oyaizu-eks-spoke-prod/registration
        property: clusterName
    - secretKey: clusterArn
      remoteRef:
        key: /fleet/members/oyaizu-eks-spoke-prod/registration
        property: clusterArn
    - secretKey: clusterEndpoint
      remoteRef:
        key: /fleet/members/oyaizu-eks-spoke-prod/registration
        property: clusterEndpoint
    - secretKey: certificateAuthorityData
      remoteRef:
        key: /fleet/members/oyaizu-eks-spoke-prod/registration
        property: certificateAuthorityData
