version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: function-name
        Alias: prod
        CurrentVersion: "0"   # buildspec が自動で書き換える
        TargetVersion: "0"    # buildspec が自動で書き換える
