apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oyaizu
  name: oyaizu-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oyaizu-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oyaizu-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup
                    operator: In
                    values:
                      - sample   # ← ノードグループに付けたラベル値
      containers:
      - image: nginx
        resources:
          limits:
            memory: "700Mi"
            cpu: "0.5"
          requests:
            memory: "700Mi"
            cpu: "0.5"
        imagePullPolicy: Always
        name: oyaizu-app
        ports:
        - containerPort: 80