apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: sample-aws-secret # 任意の名前
  namespace: ack # 使用する名前空間
spec:
  name: sample-aws-secret
  secretString:
    name: sample-k8s-secret # k8s-secret.yamlのシークレット名
    namespace: ack # シークレットが存在する名前空間
    key: secret.json # 保存するシークレットの値