apiVersion: v1
kind: Secret
metadata:
  name: sample-k8s-secret # 任意の名前
  namespace: ack # 使用する名前空間
type: Opaque
stringData:
  secret.json: |
    {
      "username": "sample-user",
      "password": "sample-password"
    }